---
title: "Final Viz"
author: "Adam Ribaudo"
date: "November 20, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Combined Region Variables

```{r}
library(dplyr)
library(ggplot2)
load(".dc_model")
load("ma_fit.RData")
load(".CO_model")
ma_model <- ma_fit

dc_suspension_pred <- tibble(proficiency=predict(dc_model, data.frame(suspensions=seq(.00,1,.01), Safe_Truancy_Current_Year=rep(0,101)))^2- 0.4447553) %>% bind_cols(data.frame(rate=seq(.00,1,.01))) %>% mutate(variable="DC Suspension", region="DC")

dc_truancy_pred <- tibble(proficiency=predict(dc_model, data.frame(Safe_Truancy_Current_Year=seq(.00,1,.01), suspensions=rep(0,101)))^2- 0.4447553) %>% bind_cols(data.frame(rate=seq(.00,1,.01))) %>% mutate(variable="DC Truancy", region="DC")

#MA
ma_retention_pred <- tibble(proficiency=predict(ma_model, data.frame(retained=seq(.00,1,.01), ooss=rep(0,101),abs_ten=rep(0,101)))- ma_model$coefficients[1]) %>% bind_cols(data.frame(rate=seq(.00,1,.01))) %>% mutate(variable="MA Retention", region="MA")

ma_truancy_pred <- tibble(proficiency=predict(ma_model, data.frame(abs_ten=seq(.00,1,.01), ooss=rep(0,101),retained=rep(0,101)))- ma_model$coefficients[1]) %>% bind_cols(data.frame(rate=seq(.00,1,.01))) %>% mutate(variable="MA Truancy", region="MA")

ma_suspension_pred <- tibble(proficiency=predict(ma_model, data.frame(ooss=seq(.00,1,.01), abs_ten=rep(0,101),retained=rep(0,101)))- ma_model$coefficients[1]) %>% bind_cols(data.frame(rate=seq(.00,1,.01))) %>% mutate(variable="MA Suspension", region="MA")

#CO

CO_retention_pred <- tibble(proficiency=predict(CO_model, data.frame(RetentionRate=seq(.00,1,.01), SuspensionRate=rep(0,101),TruancyRate=rep(0,101)))- CO_model$coefficients[1]) %>% bind_cols(data.frame(rate=seq(.00,1,.01))) %>% mutate(variable="CO Retention", region="CO")

CO_truancy_pred <- tibble(proficiency=predict(CO_model, data.frame(TruancyRate=seq(.00,1,.01), SuspensionRate=rep(0,101),RetentionRate=rep(0,101)))- CO_model$coefficients[1]) %>% bind_cols(data.frame(rate=seq(.00,1,.01))) %>% mutate(variable="CO Truancy", region="CO")

CO_suspension_pred <- tibble(proficiency=predict(CO_model, data.frame(SuspensionRate=seq(.00,1,.01), TruancyRate=rep(0,101),RetentionRate=rep(0,101)))- CO_model$coefficients[1]) %>% bind_cols(data.frame(rate=seq(.00,1,.01))) %>% mutate(variable="CO Suspension", region="CO")

final_pred <- dc_suspension_pred %>% union(dc_truancy_pred) %>% union(ma_retention_pred) %>% union(ma_truancy_pred) %>% union(ma_suspension_pred) %>%union(CO_truancy_pred) %>%
  union(CO_retention_pred) %>% union(CO_suspension_pred)

#Limiting the y scale to -100% and 100% math proficiency
ggplot(final_pred) + geom_line(size=2,aes(rate,proficiency, color=variable )) + scale_y_continuous(limits=c(-1,1)) +  theme(text = element_text(size=20)) + xlab("Rate") + ylab("Math Proficiency") + labs(color="Variable") + facet_grid(cols=vars(region))

```
